name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2.0.0

      - uses: actions/upload-artifact@v4
        with:
          name: LevelImposter.dll
          path: LevelImposter/bin/Release/net6.0/LevelImposter.dll
